# Generated by Django 5.1.1 on 2024-09-19 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smehs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.AlterModelOptions(
            name='smeh',
            options={'verbose_name': 'Смешарик', 'verbose_name_plural': 'Смешарики'},
        ),
        migrations.AddField(
            model_name='smeh',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smehs.gender'),
        ),
    ]
