# Generated by Django 5.1.1 on 2024-09-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smehs', '0002_gender_alter_smeh_options_smeh_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Пол', 'verbose_name_plural': 'Пол'},
        ),
        migrations.RemoveField(
            model_name='smeh',
            name='gender_name',
        ),
    ]
