# Generated by Django 5.1.1 on 2024-10-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smehs', '0004_actor_age_type_smeh_actor_smeh_age_smeh_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeh',
            name='picture',
            field=models.ImageField(null=True, upload_to='smehs', verbose_name='Изображение'),
        ),
    ]
