# Generated by Django 5.1.1 on 2024-10-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smehs', '0005_smeh_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='picture',
            field=models.ImageField(null=True, upload_to='types', verbose_name='Изображение'),
        ),
    ]
