# Generated by Django 5.1.1 on 2024-11-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smehs', '0007_smeh_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользлватель',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
